import type { Metadata } from "next";
import { Barlow, Inter } from "next/font/google";
import "./globals.css";

const barlow = Barlow({
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-barlow",
  weight: "600",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { AuthProvider } from "./providers/AuthProvider";
import { ColumnProvider } from "./providers/TaskProvider";
import { Toaster } from "react-hot-toast";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} ${inter.variable}`}>
        <AuthProvider>
         
            <div id="myportal" />
            {children}
       
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
